commands:
  Fly: true
  God: true
  Heal: true
  opBow: true
  opEnchant: true
  setMachineGun: true
events:
  onArrowCollides: true
  onBadWeather: true
  onMachineGunHold: true
  onRightClickForMachineGunBow: true
  onTreeCapitatorTrigger: true
