name: TiagoUtils
version: ${project.version}
main: me.tiago0liveira.TiagoUtils.TiagoUtils
api-version: 1.17
authors: [ tiagooo__ ]
description: Utilities by @tiagooo__
website: https://github.com/Tiago-0liveira
